development:
  access_key_id: AKIAI3KKG52XO5SFVHKQ
  secret_access_key: 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

production:
  access_key_id: AKIAI3KKG52XO5SFVHKQ
  secret_access_key: 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