#check the existance status of plan in stripe
#Stripe::Plan.retrieve('simple_plan')
#If not exists the plan, then you have to create
#Stripe::Plan.create( :amount => 4500, :interval => 'year', :name => 'Yearly Plan', :currency => 'usd', :id => 'simple_plan' )

simple_plan:
  amount: 4500
  interval: year
  name: Yearly Plan
  currency: usd
  id: simple_plan
  
