require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DebitCardsController do

  # This should return the minimal set of attributes required to create a valid
  # DebitCard. As you add validations to DebitCard, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all debit_cards as @debit_cards" do
      debit_card = DebitCard.create! valid_attributes
      get :index
      assigns(:debit_cards).should eq([debit_card])
    end
  end

  describe "GET show" do
    it "assigns the requested debit_card as @debit_card" do
      debit_card = DebitCard.create! valid_attributes
      get :show, :id => debit_card.id.to_s
      assigns(:debit_card).should eq(debit_card)
    end
  end

  describe "GET new" do
    it "assigns a new debit_card as @debit_card" do
      get :new
      assigns(:debit_card).should be_a_new(DebitCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested debit_card as @debit_card" do
      debit_card = DebitCard.create! valid_attributes
      get :edit, :id => debit_card.id.to_s
      assigns(:debit_card).should eq(debit_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DebitCard" do
        expect {
          post :create, :debit_card => valid_attributes
        }.to change(DebitCard, :count).by(1)
      end

      it "assigns a newly created debit_card as @debit_card" do
        post :create, :debit_card => valid_attributes
        assigns(:debit_card).should be_a(DebitCard)
        assigns(:debit_card).should be_persisted
      end

      it "redirects to the created debit_card" do
        post :create, :debit_card => valid_attributes
        response.should redirect_to(DebitCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved debit_card as @debit_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        DebitCard.any_instance.stub(:save).and_return(false)
        post :create, :debit_card => {}
        assigns(:debit_card).should be_a_new(DebitCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DebitCard.any_instance.stub(:save).and_return(false)
        post :create, :debit_card => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested debit_card" do
        debit_card = DebitCard.create! valid_attributes
        # Assuming there are no other debit_cards in the database, this
        # specifies that the DebitCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DebitCard.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => debit_card.id, :debit_card => {'these' => 'params'}
      end

      it "assigns the requested debit_card as @debit_card" do
        debit_card = DebitCard.create! valid_attributes
        put :update, :id => debit_card.id, :debit_card => valid_attributes
        assigns(:debit_card).should eq(debit_card)
      end

      it "redirects to the debit_card" do
        debit_card = DebitCard.create! valid_attributes
        put :update, :id => debit_card.id, :debit_card => valid_attributes
        response.should redirect_to(debit_card)
      end
    end

    describe "with invalid params" do
      it "assigns the debit_card as @debit_card" do
        debit_card = DebitCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DebitCard.any_instance.stub(:save).and_return(false)
        put :update, :id => debit_card.id.to_s, :debit_card => {}
        assigns(:debit_card).should eq(debit_card)
      end

      it "re-renders the 'edit' template" do
        debit_card = DebitCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DebitCard.any_instance.stub(:save).and_return(false)
        put :update, :id => debit_card.id.to_s, :debit_card => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested debit_card" do
      debit_card = DebitCard.create! valid_attributes
      expect {
        delete :destroy, :id => debit_card.id.to_s
      }.to change(DebitCard, :count).by(-1)
    end

    it "redirects to the debit_cards list" do
      debit_card = DebitCard.create! valid_attributes
      delete :destroy, :id => debit_card.id.to_s
      response.should redirect_to(debit_cards_url)
    end
  end

end
