require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FurnituresController do

  # This should return the minimal set of attributes required to create a valid
  # Furniture. As you add validations to Furniture, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all furnitures as @furnitures" do
      furniture = Furniture.create! valid_attributes
      get :index
      assigns(:furnitures).should eq([furniture])
    end
  end

  describe "GET show" do
    it "assigns the requested furniture as @furniture" do
      furniture = Furniture.create! valid_attributes
      get :show, :id => furniture.id.to_s
      assigns(:furniture).should eq(furniture)
    end
  end

  describe "GET new" do
    it "assigns a new furniture as @furniture" do
      get :new
      assigns(:furniture).should be_a_new(Furniture)
    end
  end

  describe "GET edit" do
    it "assigns the requested furniture as @furniture" do
      furniture = Furniture.create! valid_attributes
      get :edit, :id => furniture.id.to_s
      assigns(:furniture).should eq(furniture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Furniture" do
        expect {
          post :create, :furniture => valid_attributes
        }.to change(Furniture, :count).by(1)
      end

      it "assigns a newly created furniture as @furniture" do
        post :create, :furniture => valid_attributes
        assigns(:furniture).should be_a(Furniture)
        assigns(:furniture).should be_persisted
      end

      it "redirects to the created furniture" do
        post :create, :furniture => valid_attributes
        response.should redirect_to(Furniture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved furniture as @furniture" do
        # Trigger the behavior that occurs when invalid params are submitted
        Furniture.any_instance.stub(:save).and_return(false)
        post :create, :furniture => {}
        assigns(:furniture).should be_a_new(Furniture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Furniture.any_instance.stub(:save).and_return(false)
        post :create, :furniture => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested furniture" do
        furniture = Furniture.create! valid_attributes
        # Assuming there are no other furnitures in the database, this
        # specifies that the Furniture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Furniture.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => furniture.id, :furniture => {'these' => 'params'}
      end

      it "assigns the requested furniture as @furniture" do
        furniture = Furniture.create! valid_attributes
        put :update, :id => furniture.id, :furniture => valid_attributes
        assigns(:furniture).should eq(furniture)
      end

      it "redirects to the furniture" do
        furniture = Furniture.create! valid_attributes
        put :update, :id => furniture.id, :furniture => valid_attributes
        response.should redirect_to(furniture)
      end
    end

    describe "with invalid params" do
      it "assigns the furniture as @furniture" do
        furniture = Furniture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Furniture.any_instance.stub(:save).and_return(false)
        put :update, :id => furniture.id.to_s, :furniture => {}
        assigns(:furniture).should eq(furniture)
      end

      it "re-renders the 'edit' template" do
        furniture = Furniture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Furniture.any_instance.stub(:save).and_return(false)
        put :update, :id => furniture.id.to_s, :furniture => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested furniture" do
      furniture = Furniture.create! valid_attributes
      expect {
        delete :destroy, :id => furniture.id.to_s
      }.to change(Furniture, :count).by(-1)
    end

    it "redirects to the furnitures list" do
      furniture = Furniture.create! valid_attributes
      delete :destroy, :id => furniture.id.to_s
      response.should redirect_to(furnitures_url)
    end
  end

end
