require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InHomeSafeOrVaultsController do

  # This should return the minimal set of attributes required to create a valid
  # InHomeSafeOrVault. As you add validations to InHomeSafeOrVault, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all in_home_safe_or_vaults as @in_home_safe_or_vaults" do
      in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
      get :index
      assigns(:in_home_safe_or_vaults).should eq([in_home_safe_or_vault])
    end
  end

  describe "GET show" do
    it "assigns the requested in_home_safe_or_vault as @in_home_safe_or_vault" do
      in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
      get :show, :id => in_home_safe_or_vault.id.to_s
      assigns(:in_home_safe_or_vault).should eq(in_home_safe_or_vault)
    end
  end

  describe "GET new" do
    it "assigns a new in_home_safe_or_vault as @in_home_safe_or_vault" do
      get :new
      assigns(:in_home_safe_or_vault).should be_a_new(InHomeSafeOrVault)
    end
  end

  describe "GET edit" do
    it "assigns the requested in_home_safe_or_vault as @in_home_safe_or_vault" do
      in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
      get :edit, :id => in_home_safe_or_vault.id.to_s
      assigns(:in_home_safe_or_vault).should eq(in_home_safe_or_vault)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InHomeSafeOrVault" do
        expect {
          post :create, :in_home_safe_or_vault => valid_attributes
        }.to change(InHomeSafeOrVault, :count).by(1)
      end

      it "assigns a newly created in_home_safe_or_vault as @in_home_safe_or_vault" do
        post :create, :in_home_safe_or_vault => valid_attributes
        assigns(:in_home_safe_or_vault).should be_a(InHomeSafeOrVault)
        assigns(:in_home_safe_or_vault).should be_persisted
      end

      it "redirects to the created in_home_safe_or_vault" do
        post :create, :in_home_safe_or_vault => valid_attributes
        response.should redirect_to(InHomeSafeOrVault.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved in_home_safe_or_vault as @in_home_safe_or_vault" do
        # Trigger the behavior that occurs when invalid params are submitted
        InHomeSafeOrVault.any_instance.stub(:save).and_return(false)
        post :create, :in_home_safe_or_vault => {}
        assigns(:in_home_safe_or_vault).should be_a_new(InHomeSafeOrVault)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InHomeSafeOrVault.any_instance.stub(:save).and_return(false)
        post :create, :in_home_safe_or_vault => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested in_home_safe_or_vault" do
        in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
        # Assuming there are no other in_home_safe_or_vaults in the database, this
        # specifies that the InHomeSafeOrVault created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InHomeSafeOrVault.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => in_home_safe_or_vault.id, :in_home_safe_or_vault => {'these' => 'params'}
      end

      it "assigns the requested in_home_safe_or_vault as @in_home_safe_or_vault" do
        in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
        put :update, :id => in_home_safe_or_vault.id, :in_home_safe_or_vault => valid_attributes
        assigns(:in_home_safe_or_vault).should eq(in_home_safe_or_vault)
      end

      it "redirects to the in_home_safe_or_vault" do
        in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
        put :update, :id => in_home_safe_or_vault.id, :in_home_safe_or_vault => valid_attributes
        response.should redirect_to(in_home_safe_or_vault)
      end
    end

    describe "with invalid params" do
      it "assigns the in_home_safe_or_vault as @in_home_safe_or_vault" do
        in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InHomeSafeOrVault.any_instance.stub(:save).and_return(false)
        put :update, :id => in_home_safe_or_vault.id.to_s, :in_home_safe_or_vault => {}
        assigns(:in_home_safe_or_vault).should eq(in_home_safe_or_vault)
      end

      it "re-renders the 'edit' template" do
        in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InHomeSafeOrVault.any_instance.stub(:save).and_return(false)
        put :update, :id => in_home_safe_or_vault.id.to_s, :in_home_safe_or_vault => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested in_home_safe_or_vault" do
      in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
      expect {
        delete :destroy, :id => in_home_safe_or_vault.id.to_s
      }.to change(InHomeSafeOrVault, :count).by(-1)
    end

    it "redirects to the in_home_safe_or_vaults list" do
      in_home_safe_or_vault = InHomeSafeOrVault.create! valid_attributes
      delete :destroy, :id => in_home_safe_or_vault.id.to_s
      response.should redirect_to(in_home_safe_or_vaults_url)
    end
  end

end
