require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InsurancesController do

  # This should return the minimal set of attributes required to create a valid
  # Insurance. As you add validations to Insurance, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all insurances as @insurances" do
      insurance = Insurance.create! valid_attributes
      get :index
      assigns(:insurances).should eq([insurance])
    end
  end

  describe "GET show" do
    it "assigns the requested insurance as @insurance" do
      insurance = Insurance.create! valid_attributes
      get :show, :id => insurance.id.to_s
      assigns(:insurance).should eq(insurance)
    end
  end

  describe "GET new" do
    it "assigns a new insurance as @insurance" do
      get :new
      assigns(:insurance).should be_a_new(Insurance)
    end
  end

  describe "GET edit" do
    it "assigns the requested insurance as @insurance" do
      insurance = Insurance.create! valid_attributes
      get :edit, :id => insurance.id.to_s
      assigns(:insurance).should eq(insurance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Insurance" do
        expect {
          post :create, :insurance => valid_attributes
        }.to change(Insurance, :count).by(1)
      end

      it "assigns a newly created insurance as @insurance" do
        post :create, :insurance => valid_attributes
        assigns(:insurance).should be_a(Insurance)
        assigns(:insurance).should be_persisted
      end

      it "redirects to the created insurance" do
        post :create, :insurance => valid_attributes
        response.should redirect_to(Insurance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved insurance as @insurance" do
        # Trigger the behavior that occurs when invalid params are submitted
        Insurance.any_instance.stub(:save).and_return(false)
        post :create, :insurance => {}
        assigns(:insurance).should be_a_new(Insurance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Insurance.any_instance.stub(:save).and_return(false)
        post :create, :insurance => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested insurance" do
        insurance = Insurance.create! valid_attributes
        # Assuming there are no other insurances in the database, this
        # specifies that the Insurance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Insurance.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => insurance.id, :insurance => {'these' => 'params'}
      end

      it "assigns the requested insurance as @insurance" do
        insurance = Insurance.create! valid_attributes
        put :update, :id => insurance.id, :insurance => valid_attributes
        assigns(:insurance).should eq(insurance)
      end

      it "redirects to the insurance" do
        insurance = Insurance.create! valid_attributes
        put :update, :id => insurance.id, :insurance => valid_attributes
        response.should redirect_to(insurance)
      end
    end

    describe "with invalid params" do
      it "assigns the insurance as @insurance" do
        insurance = Insurance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Insurance.any_instance.stub(:save).and_return(false)
        put :update, :id => insurance.id.to_s, :insurance => {}
        assigns(:insurance).should eq(insurance)
      end

      it "re-renders the 'edit' template" do
        insurance = Insurance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Insurance.any_instance.stub(:save).and_return(false)
        put :update, :id => insurance.id.to_s, :insurance => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested insurance" do
      insurance = Insurance.create! valid_attributes
      expect {
        delete :destroy, :id => insurance.id.to_s
      }.to change(Insurance, :count).by(-1)
    end

    it "redirects to the insurances list" do
      insurance = Insurance.create! valid_attributes
      delete :destroy, :id => insurance.id.to_s
      response.should redirect_to(insurances_url)
    end
  end

end
