require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WillAndTrustsController do

  # This should return the minimal set of attributes required to create a valid
  # WillAndTrust. As you add validations to WillAndTrust, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all will_and_trusts as @will_and_trusts" do
      will_and_trust = WillAndTrust.create! valid_attributes
      get :index
      assigns(:will_and_trusts).should eq([will_and_trust])
    end
  end

  describe "GET show" do
    it "assigns the requested will_and_trust as @will_and_trust" do
      will_and_trust = WillAndTrust.create! valid_attributes
      get :show, :id => will_and_trust.id.to_s
      assigns(:will_and_trust).should eq(will_and_trust)
    end
  end

  describe "GET new" do
    it "assigns a new will_and_trust as @will_and_trust" do
      get :new
      assigns(:will_and_trust).should be_a_new(WillAndTrust)
    end
  end

  describe "GET edit" do
    it "assigns the requested will_and_trust as @will_and_trust" do
      will_and_trust = WillAndTrust.create! valid_attributes
      get :edit, :id => will_and_trust.id.to_s
      assigns(:will_and_trust).should eq(will_and_trust)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WillAndTrust" do
        expect {
          post :create, :will_and_trust => valid_attributes
        }.to change(WillAndTrust, :count).by(1)
      end

      it "assigns a newly created will_and_trust as @will_and_trust" do
        post :create, :will_and_trust => valid_attributes
        assigns(:will_and_trust).should be_a(WillAndTrust)
        assigns(:will_and_trust).should be_persisted
      end

      it "redirects to the created will_and_trust" do
        post :create, :will_and_trust => valid_attributes
        response.should redirect_to(WillAndTrust.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved will_and_trust as @will_and_trust" do
        # Trigger the behavior that occurs when invalid params are submitted
        WillAndTrust.any_instance.stub(:save).and_return(false)
        post :create, :will_and_trust => {}
        assigns(:will_and_trust).should be_a_new(WillAndTrust)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WillAndTrust.any_instance.stub(:save).and_return(false)
        post :create, :will_and_trust => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested will_and_trust" do
        will_and_trust = WillAndTrust.create! valid_attributes
        # Assuming there are no other will_and_trusts in the database, this
        # specifies that the WillAndTrust created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WillAndTrust.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => will_and_trust.id, :will_and_trust => {'these' => 'params'}
      end

      it "assigns the requested will_and_trust as @will_and_trust" do
        will_and_trust = WillAndTrust.create! valid_attributes
        put :update, :id => will_and_trust.id, :will_and_trust => valid_attributes
        assigns(:will_and_trust).should eq(will_and_trust)
      end

      it "redirects to the will_and_trust" do
        will_and_trust = WillAndTrust.create! valid_attributes
        put :update, :id => will_and_trust.id, :will_and_trust => valid_attributes
        response.should redirect_to(will_and_trust)
      end
    end

    describe "with invalid params" do
      it "assigns the will_and_trust as @will_and_trust" do
        will_and_trust = WillAndTrust.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WillAndTrust.any_instance.stub(:save).and_return(false)
        put :update, :id => will_and_trust.id.to_s, :will_and_trust => {}
        assigns(:will_and_trust).should eq(will_and_trust)
      end

      it "re-renders the 'edit' template" do
        will_and_trust = WillAndTrust.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WillAndTrust.any_instance.stub(:save).and_return(false)
        put :update, :id => will_and_trust.id.to_s, :will_and_trust => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested will_and_trust" do
      will_and_trust = WillAndTrust.create! valid_attributes
      expect {
        delete :destroy, :id => will_and_trust.id.to_s
      }.to change(WillAndTrust, :count).by(-1)
    end

    it "redirects to the will_and_trusts list" do
      will_and_trust = WillAndTrust.create! valid_attributes
      delete :destroy, :id => will_and_trust.id.to_s
      response.should redirect_to(will_and_trusts_url)
    end
  end

end
